name: Publish

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x
      - name: Get version
        id: version
        run: |
          $version = (cat plugin.json | ConvertFrom-Json).Version
          ac $env:GITHUB_OUTPUT "version=$version"
      - name: Build
        run: |
          dotnet publish -c Release
          7z a -tzip "RiderWorkFlow.zip" "RiderWorkFlow/*"
          rm -r "RiderWorkFlow.zip"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: RiderWorkFlow.zip
          tag_name: ${{ steps.version.outputs.version }}
