name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'plugin.json'
        prop_path: 'Version'    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore 'RiderWorkFlow.csproj'
    - name: Build
      run: dotnet build 'RiderWorkFlow.csproj' --no-restore
    - name: Dotnet Publish
      run: |
        dotnet publish 'RiderWorkFlow.csproj' -c Release -o "RiderWorkFlow"
        7z a -tzip "RiderWorkFlow.zip" "/*"
        rm -r "RiderWorkFlow"
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: "RiderWorkFlow.zip"
        tag_name: "v${{steps.version.outputs.prop}}"        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
